"""create interview feedback table

Revision ID: 127d39341e56
Revises: 4978f8104a2a
Create Date: 2025-12-25 01:54:16.900232+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '127d39341e56'
down_revision: Union[str, None] = '4978f8104a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('technical_accuracy_score', sa.Integer(), nullable=False),
    sa.Column('communication_clarity_score', sa.Integer(), nullable=False),
    sa.Column('problem_solving_score', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('technical_feedback', sa.Text(), nullable=False),
    sa.Column('communication_feedback', sa.Text(), nullable=False),
    sa.Column('problem_solving_feedback', sa.Text(), nullable=False),
    sa.Column('relevance_feedback', sa.Text(), nullable=False),
    sa.Column('overall_comments', sa.Text(), nullable=True),
    sa.Column('knowledge_gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('learning_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_feedbacks_session_id'), 'interview_feedbacks', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_feedbacks_session_id'), table_name='interview_feedbacks')
    op.drop_table('interview_feedbacks')
    # ### end Alembic commands ###
