"""add encrypted_api_key to users

Revision ID: 074baeca0fa0
Revises: 75cc412b7425
Create Date: 2025-12-21 05:10:24.591957+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "074baeca0fa0"
down_revision: Union[str, None] = "75cc412b7425"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("encrypted_api_key", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "encrypted_api_key")
    # ### end Alembic commands ###
