"""add_indexes_to_interview_session

Revision ID: 00bdc4df1e2f
Revises: 20251227_0200
Create Date: 2025-12-27 03:44:37.394918+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "00bdc4df1e2f"
down_revision: Union[str, None] = "20251227_0200"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_interview_sessions_created_at"),
        "interview_sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_sessions_status"),
        "interview_sessions",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_interview_sessions_status"), table_name="interview_sessions")
    op.drop_index(
        op.f("ix_interview_sessions_created_at"), table_name="interview_sessions"
    )
    # ### end Alembic commands ###
