"""add composite index on job_postings user_id created_at

Revision ID: e04d050fcfa2
Revises: 2d7b65cabd5b
Create Date: 2025-12-22 12:20:44.472655+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04d050fcfa2'
down_revision: Union[str, None] = '2d7b65cabd5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_job_postings_user_id_created_at', 'job_postings', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_postings_user_id_created_at', table_name='job_postings')
    # ### end Alembic commands ###
